name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # или используйте нужную вам платформу, например, 'windows-latest'
    
    strategy:
      matrix:
        python-version: [3.14.0-alpha]  # Указываем ваши версии Python, включая стабильные и альфа-версии
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}  # Автоматически подставляется версия из матрицы

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Устанавливаем зависимости из файла requirements.txt

    - name: Run tests
      run: |
        pytest  # Запуск тестов с использованием pytest
